### ISSUE TITLE
Feature: User can connect their Spotify account

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#1]
## 💰 Motivation

Users need to connect their Spotify account to the app so they can use playlists and listen to songs.

## 📐 Plan

Use OAuth 2.0 authorization code flow with PKCE to request the user to authorize the app to access Spotify data for their message in a bottle. https://developer.spotify.com/documentation/general/guides/authorization/code-flow/
https://www.oauth.com/playground/authorization-code-with-pkce.html

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create SpotifyLogin component
  - [x] Create a click event handler initiateSpotifyLogin
    - [x] Generate a code verifier
    - [x] Generate a code challenge by hashing the code verifier
    - [x] Generate a state
    - [x] Set the state and code verifier in session storage to be checked later
    - [x] Construct the authorization url with query parameters
    - [x] Open the Spotify authorization page
  - [x] Return a React element that contains a button with an onClick prop with the event handler initiateSpotifyLogin
 - [x] Create SpotifyAuthRedirect component
   - [x] When the component mounts, create a new URLSearchParams object with the callback url
   - [x] Create a new FormData object with the query parameters code and state to be sent back to Spotify for an access token 
   - [x] Check that state parameter from the callback matches the state parameter provided in the authorization URI
   - [x] If the states don't match, stop the authentication flow
   - [x] Otherwise, make a POST request to the /api/token endpoint to exchange the authorization code received in the callback for an Access Token
   - [x] Use Access Token in GET request for current user's data
   - [x] Get the user's display name and update the UI to show it
- [x] In app.jsx, if the current path is '/',
  - [x] Return a React element of type SpotifyLogin
- [x] If the path is 'callback'
  - [x] Return a React element of type SpotifyAuthRedirect

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
