### ISSUE TITLE
Feature: User can create a message in a bottle

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#2]
## 💰 Motivation

Users want to create a slideshow containing music, images, and text to share a memory with someone.

## 📐 Plan

Create a form that the user can fill out with the media they want to share, then save their inputs to the database.
https://developer.spotify.com/console/get-search-item/

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to create "bottles" table

### ☁️ Server

- [x] Update `server/index.js` to have a route handler that handles POST requests to the /api/messages path
- [x] Update `server/index.js` to have a route handler that handles POST requests to the /api/uploads path
- [x] Create an uploads middleware to handle file uploads
- [x] If any of the form inputs are missing, throw a new ClientError with status code 400 and tell the user that all fields are required
- [x] Insert the values into the "mementos" column of the "bottles" table
- [x] Respond with the inserted row data
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update SpotifyAuthRedirect component to have a Link that goes to /api/messages
- [x] Update App component to have another Route with a path to '/api/messages' and element MessageForm component
- [x] Create a MessageForm component
- [x] The form takes in a 'Number of Slides' input that will determine how many slide forms will be rendered after the current form is submitted
- [x] Create a button that goes to the slides portion of the form
- [x] The next pages of the form are rendered based on how many slides were specified on the message info form
- [x] Each page has buttons that will take you to the previous page or to the next
- [x] On the last page, there is a submit button instead of a next page button
- [x] When the user chooses an image, immediately upload the image, get the url from the server and save the url to state
- [x] Post the inputs to the mementos column of the bottles table
- [x] Add a button that allows the user to exit out of the form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
