### ISSUE TITLE
Bug: No pop-ups

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#24]
#### Desired Behavior

> ##### The app should ...

This app opens up the Spotify authorization page when the shell button is clicked.

#### Actual Behavior

> ##### The app does this instead ...

App doesn't work on Safari because pop-ups are blocked.

#### Steps to Reproduce

> ##### To trigger the bug, you must ...

Open the app on Safari, click on the shell to connect to Spotify, nothing happens!

## ✅ Task List

> ##### Commit checklist for tasks needed to fix the bug.

- [x] Turn shell button back into an anchor tag
- [x] Remove onClick prop
- [x] Call SpotifyLogin method as soon as the component mounts
- [x] Save the auth url in the state
- [x] Set the href of the anchor tag to the auth url
