### ISSUE TITLE
Feature: User can add songs and a playlist from Spotify to their message

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#3]
## 💰 Motivation

Users should be able to add a playlist they made or a relevant playlist to their message, as well as songs for each slide.

## 📐 Plan

Use the playlist id provided to retrieve a playlist from Spotify and add it to the database.
Use the song title and artist to search for a track and add it to the database.
https://developer.spotify.com/console/get-playlist/

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include a "playlistId" column

### ☁️ Server

- [x] Update `server/index.js` to have the POST handler for '/api/messages' send the playlistId variable to the database
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update MessageForm component to have an input for the playlist ID
- [x] Get the Spotify ID from the link provided
- [x] Add the ID to the state
- [x] Update SlideForm component to have an input for the Spotify link to the song 
- [x] Get the Spotify ID from the link provided
- [x] Add the ID to the state

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
