### ISSUE TITLE
Feature: User can view the message in a bottle they made

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#4]
## 💰 Motivation

Users need to see how their message will look to the recipient to make sure they like the output.

## 📐 Plan

Take the user inputs from the message form and use them to render the message slideshow.
https://materializecss.com/carousel.html

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a route handler that handles GET requests to the /api/messages/:bottleId
- [x] Query the database for the row that has the same bottleId value as the current user's and return the whole row
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update SlideForm component to get the bottleId property of the bottle object sent back from the server and save it to the state
- [x] Create UserActionMenu component
- [x] Create ViewMessage component
- [x] Update App component to have routes to the UserActionMenu component at path '/menu'
- [x] Update App component to have routes to the ViewMessage component at path '/api/messages/:bottleId'
- [x] Update SlideForm component to send the user to '/menu' path when the form is submitted
- [x] Add a button that opens the ViewMessage component
- [x] Send a GET request to 'api/messages/:bottleId' to retrieve the current user's message in a bottle data
- [x] Save the response in the state
- [x] Render the intro slide of the message
- [x] Render the content slides based on how many mementos objects there are
- [x] Include an exit button that will take the user back to the UserActionMenu

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
