### ISSUE TITLE
Feature: User can send the message in a bottle to someone and the recipient gets an email with a link to it

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#7]
## 💰 Motivation

Users want to share their message with someone.

## 📐 Plan

Send an email to the recipient using the email the user provided, containing the id of the message and a link to the application.
https://docs.sendgrid.com/

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to have a route handler that handles POST requests to the /api/send
- [x] Query the database for message data using the bottleId sent in the request
- [x] Send an email using the recipientEmail, messageTitle, recipientName, senderName, and bottleId values
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create SendMessage component to send the message in an email
- [x] Send a GET request to 'api/messages/:bottleId' to get the recipient email
- [x] Send a POST request to 'api/send' with the bottleId in the request body
- [x] Create a link that will send the user back to the SpotifyLogin page
- [x] Create a link that will send the user back to the UserActionMenu
- [x] Update App component to have routes to the UserActionMenu component at path '/send'
- [x] Update UserActionMenu component to have a link to the SendMessage component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
