### ISSUE TITLE
Feature: User can open a message in a bottle sent to them

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#8]
## 💰 Motivation

Users want to view a message in a bottle sent to them.

## 📐 Plan

Create a search form that takes a bottle id as an input, and retrieve the message data from the database by using the bottle id. Render the message using the data.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` have the POST route handler for '/api/send' to have a link in the email with path '/messages/recipient/:bottleId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update App component to have a route to ViewMessage with path '/messages/:user/:bottleId
- [x] Update ViewMessage component to check if the url param 'user' is 'recipient'
- [x] Don't show the recipient the UserActionMenu, redirect to SpotifyLogin

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
