### ISSUE TITLE
Feature: User can play music within the app

### ISSUE THREAD

**Issue by jamiecafirma** [jamiecafirma/message-in-a-bottle#9]
## 💰 Motivation

Users want to listen to the music that comes along with the message.

## 📐 Plan

Retrieve the track the sender wanted from the database and play it.
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-track

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![X - 20](https://user-images.githubusercontent.com/87781879/141695623-cd9b5a09-7915-4fa6-bed0-dc8269b04e82.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Fetch the track data from Spotify
- [ ] Update ViewMessage component to show the current slide's song using the song id from the message data
- [ ] Play the song audio
- [ ] Add a button that will toggle the sound of the page

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
